### ISSUE TITLE
Several array out-of-bound accesses in bricks puzzle

### ISSUE THREAD

**Issue by SteffenBauer** [x-sheep/puzzles-unreleased#3]
I ran bricks with valgrind; after replacing "UI_UPDATE" with "MOVE_UI_UPDATE" to adjust to the newest upstream changes.
I got several "Invalid read of size 4" warnings.
The affected functions are `new_game_desc`, `bricks_fill_grid`, and `bricks_validate_threes`.

For example, line 868 in `new_game_desc` loops from 0 to w*h with the upper bound included, but `state->grid` is only allocated `w*h`, so `w*h-1` is the highest accessible array entry.

Similiar but a little bit more complicated illegal accesses occur in the other mentioned functions.

**Comment by x-sheep** [comment]
Hi Steffen,

I no longer have the capacity to work on this project. If you want to make a Pull Request to address these issues, I'd be happy to merge them.

**Comment by SteffenBauer** [comment]
Ok, will look into it.
